language: php

services:
  - mysql

php:
  - 7.3
  - 7.4
  - 8.0

install:
  - composer install --prefer-dist --no-interaction --no-suggest
  - mysql -e 'CREATE DATABASE test;'

script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
