language: php

services:
- mysql

php:
- 7.1
- 7.2
- 7.3

install: composer install --prefer-dist --no-interaction --no-suggest

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
