language: php

services:
- mysql

php:
- 7.2
- 7.3
- 7.4

install:
- composer install --prefer-dist --no-interaction --no-suggest
- mysql -e 'CREATE DATABASE test;'

script:
- composer stan
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
