services:
  php:
    build:
      context: .
      args:
        USER: $USER
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_mode=req remote_port=9000 remote_host=$XDEBUG_REMOTE_HOST remote_connect_back=0"
      PHP_IDE_CONFIG: "serverName=laravel-db-ready"
    tty: true

  mysql:
    image: mysql:5.7
    tmpfs: /var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
