name: "Validate"
on:
  pull_request:
  push:
    branches:
      - master

env:
  REQUIRED_PHP_EXTENSIONS: mysqli, pdo_mysql

# Using ubuntu-18.04 because it has MySQL 5.7.

jobs:
  static-analysis:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1
        laravel-version:
          - ^8
          - ^9
        exclude:
          - php-version: 7.4
            laravel-version: ^9

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: ${{ env.REQUIRED_PHP_EXTENSIONS }}
          php-version: ${{ matrix.php-version }}

      - run: composer require illuminate/contracts:${{ matrix.laravel-version }} --no-interaction --prefer-dist --no-progress

      - uses: ramsey/composer-install@v2

      - run: vendor/bin/phpstan

  tests:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1
        laravel-version:
          - ^8
          - ^9
        exclude:
          - php-version: 7.4
            laravel-version: ^9

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          extensions: ${{ env.REQUIRED_PHP_EXTENSIONS }}
          php-version: ${{ matrix.php-version }}

      - run: composer require illuminate/contracts:${{ matrix.laravel-version }} --no-interaction --prefer-dist --no-progress

      - uses: ramsey/composer-install@v2

      - run: |
          sudo systemctl start mysql.service
          mysql --user=root --password=root --execute='CREATE DATABASE test;'

      - run: vendor/bin/phpunit --colors=always --verbose
